version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0

workflows:
  build:
    jobs:
      - cypress/install:
        build: 'npm run build'
      - cypress/run:
        requires:
          - cypress/install
        record: true
        parallel: true
        parallelism: 4
        group: 'all tests'
        start: 'npm-start'
        wait-on: 'http://localhost:3000'