version: 2.1

orbs:
  cypress: cypress-io/cypress@2.2.0

workflows:
  build:
    jobs:
      - cypress/run:
          record: true
          parallel: true
          parallelism: 4
          group: 'all tests'
          start: 'npm-start'